[package]
name = "murdock-cli"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

description = "A CLI client for Murdock-NG"
repository = "https://github.com/murdock-ng/murdock-cli"
homepage = "https://github.com/murdock-ng/murdock-cli"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
anyhow = "1.0.68"
chrono = "0.4.23"
clap = { version = "3.2.23", features = ["cargo", "env"] }
derive_builder = "0.12.0"
indexmap = { version = "1.9.2", features = ["serde"] }
murdock-api = { version = "1.0.0", path = "./murdock-api" }
platform-dirs = "0.3.0"
reqwest = { version = "0.11.14", features = ["blocking"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
tokio = { version = "1.24.2", features = ["full"] }
