[package]
name = "murdock-cli"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
edition = "2021"

description = "A CLI client for Murdock-NG"
repository = "https://github.com/murdock-ng/murdock-cli"
homepage = "https://github.com/murdock-ng/murdock-cli"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["cargo", "env"] }
derive_builder = "0.20.0"
indexmap = { version = "2.2.3", features = ["serde"] }
murdock-api = { version = "1.0.0", path = "./murdock-api" }
platform-dirs = "0.3.0"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_yaml = "0.9.32"
tokio = { version = "1.26.0", features = ["full"] }
